language: node_js
node_js:
- '4.2'
before_script:
- npm install grunt-cli -g
script: npm test
env:
- CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
deploy:
  provider: npm
  email: henri.bergius@iki.fi
  api_key:
    secure: RyBYo76Hrq+ZYht2ZVIYAa+zS15jH0NN41qd6v6Yvd9Ub45rqGgtonJVF6Y01nWSpGgCIWDhbMBwmiJF936xC6qZ1yNFW67kyUFRja/+neoi+2M1en83yZQBmR5Nzghf0K30uXT9OyyXE+YKuDC0SF47vBMhTWYZpfWzOO9XTf4=
  on:
    tags: true
    repo: noflo/noflo-markdown
